%YAML:1.0
cameras:
    - {T_SC:
       [ -0.999888912384, 0.013093434084, 0.00712213984611, 0.0412812028429,
         -0.013001186564, -0.99983293668, 0.0128478744074, 0.00163024513463,
         0.00728917279446, 0.0127538508987, 0.999892097802, 0.0107524601881,
          0.0, 0.0, 0.0, 1.0],
       image_dimension: [640, 400],
       distortion_coefficients: [-0.155998018039, -0.0175543441406, -0.000184566842241, 0.0109804498701],
       distortion_type: equidistant,
       focal_length: [443.816690765, 443.627454984],
       principal_point: [314.087884109, 207.206490242]}

    - {T_SC:
       [ -0.999889157331, 0.0138376192711, -0.0054948470795, -0.0390291417223,
         -0.0139632921903, -0.999625557747, 0.0235323345826, 0.000747631578312,
         -0.00516715809007, 0.0236064523511, 0.999707975303, 0.0104490910215,
          0.0, 0.0, 0.0, 1.0],
       image_dimension: [640, 400],
       distortion_coefficients: [-0.154855698556, -0.0325773385198, 0.0353373902222, -0.0137353545812],
       distortion_type: equidistant,
       focal_length: [441.662436415, 441.244816167],
       principal_point: [320.872967887, 205.655943918]}


camera_params:
    camera_rate: 20 # just to manage the expectations of when there should be frames arriving
    sigma_absolute_translation: 0.0 # The standard deviation of the camera extrinsics translation, e.g. 1.0e-10 for online-calib [m].
    sigma_absolute_orientation: 0.0 # The standard deviation of the camera extrinsics orientation, e.g. 1.0e-3 for online-calib [rad].
    sigma_c_relative_translation: 0.0 # The std. dev. of the cam. extr. transl. change between frames, e.g. 1.0e-6 for adaptive online calib (not less for numerics) [m].
    sigma_c_relative_orientation: 0.0 # The std. dev. of the cam. extr. orient. change between frames, e.g. 1.0e-6 for adaptive online calib (not less for numerics) [rad].
    timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance

imu_params:
    a_max: 39.1836 # acceleration saturation [m/s^2] # 4 * g
    g_max: 8.73 # gyro saturation [rad/s]            # 500 * pi / 180
    sigma_g_c: 0.0021923690143745844 # gyro noise density [rad/s/sqrt(Hz)]
    sigma_a_c: 0.02165722852325273 # accelerometer noise density [m/s^2/sqrt(Hz)]
    sigma_bg: 0.03 # gyro bias prior [rad/s]
    sigma_ba: 0.1 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 1.4221215955051228e-05 # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_aw_c: 0.000381538711491782 # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    tau: 3600.0 # reversion time constant, currently not in use [s]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    a0: [ 0.0, 0.0, 0.0 ] # Accelerometer bias [m/s^2]
    imu_rate: 200
    # tranform Body-Sensor (IMU)
    T_BS:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]

# Estimator parameters
numKeyframes: 5 # number of keyframes in optimisation window
numImuFrames: 3 # number of frames linked by most recent nonlinear IMU error terms

# ceres optimization options
ceres_options:
    minIterations: 3   # minimum number of iterations always performed
    maxIterations: 10  # never do more than these, even if not converged
    timeLimit: 0.035   # [s] negative values will set the an unlimited time limit

# detection
detection_options:
    threshold: 40.0      # detection threshold. By default the uniformity radius in pixels
    octaves: 0           # number of octaves for detection. 0 means single-scale at highest resolution
    maxNoKeypoints: 400  # restrict to a maximum of this many keypoints per image (strongest ones)

# delay of images [s]:
imageDelay: 0.0  # in case you are using a custom setup, you will have to calibrate this. 0 for the VISensor.

# display debug images?
displayImages: true  # displays debug video and keyframe matches. May be slow.

# use direct driver
useDriver: true 

# some options for how and what to publish -- optional in ROS-free version
publishing_options:
    publish_rate: 200                  # rate at which odometry updates are published only works properly if imu_rate/publish_rate is an integer!!
    publishLandmarks: true             # select, if you want to publish landmarks at all
    landmarkQualityThreshold: 1.0e-2   # landmark with lower quality will not be published
    maximumLandmarkQuality: 0.05       # landmark with higher quality will be published with the maximum colour intensity
    maxPathLength: 20                  # maximum length of the published path
    publishImuPropagatedState: true    # Should the state that is propagated with IMU messages be published? Or just the optimized ones?
    # provide custom World frame Wc
    T_Wc_W:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]
    trackedBodyFrame: B                # B or S, the frame of reference that will be expressed relative to the selected worldFrame
    velocitiesFrame: Wc                # Wc, B or S,  the frames in which the velocities of the selected trackedBodyFrame will be expressed in

